project_id = "nmvxaplrijzknqbbpdck"

[auth]
site_url = "https://nmvxaplrijzknqbbpdck.supabase.co"
additional_redirect_urls = ["https://localhost:3000"]

[db]
port = 5432

[api]
enabled = true
port = 54321

[functions]
verify_jwt = true

[functions.validate-codeforces-user]
verify_jwt = false

[functions.room-management]
verify_jwt = false

[functions.random-cp-questions]
verify_jwt = false

[functions.duel-management]
verify_jwt = false